Okay, just trying to get the package to create a apache2 config file and whatnot

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -3,7 +3,7 @@
 #
 # see: dh_installdeb(1)
 
-set -e
+set -x
 
 # summary of how this script can be called:
 #        * <postinst> `configure' <most-recently-configured-version>
@@ -17,12 +17,33 @@ set -e
 # for details, see http://www.debian.org/doc/debian-policy/ or
 # the debian-policy package
 
-
+DESTDIR=
+APACHE2_SITES_AVAILABLE=$DESTDIR/etc/apache2/sites-available/
+HTML=$DESTDIR/var/www/
+APACHE2_RESTART=apache2ctl restart
+APACHE2_ENABLE_SITE=a2ensite
+APACHE2_DISABLE_SITE=a2disite
+SITE_NAME=django-library
+HTMLPAYLOAD=$HTML$SITE_NAME
+HOSTNAME=local2.bibliodira.org
+ 
 case "$1" in
     configure)
+       if [ -f "$APACHE2_SITES_AVAILABLE$HOSTNAME" ]; then 
+            echo "Error: can't recreate the django-library"; exit 2;
+        else 
+            cat django-library.apache2 | sed 's|##HTMLPAYLOAD##|$HTMLPAYLOAD|' | sed 's|##HOSTNAME##|$HOSTNAME|' > $APACHE2_SITES_AVAILABLE$HOSTNAME ; \
+            $APACHE2_ENABLE_SITE $HOSTNAME ;
+            $APACHE2_RESTART ;
+        fi ; 
+
+
     ;;
 
     abort-upgrade|abort-remove|abort-deconfigure)
+        if [ -f "$APACHE2_SITES_AVAILABLE$HOSTNAME" ]; then
+            rm $APACHE2_SITES_AVAILABLE$HOSTNAME ;
+        fi ;
     ;;
 
     *)
